#!/bin/zsh
export PYDEVD_DISABLE_FILE_VALIDATION=1

rm -fR html

cd src
./create_toc.py
cd ..


cp src/_templates/* `python -c "import sphinx_book_theme as sbt; import os; print(os.path.dirname(sbt.__file__) + '/theme/sphinx_book_theme/components/')"`

jupyter-book build src

mv src/_build/html .

open html/index.html
