#!/usr/bin/env python3

"""
Tranform toc.md into _toc.yml.

Removes [] and ().
"""

with open('src/toc.md', 'r') as source:
    with open('src/_toc.yml', 'w') as destination:
        destination.writelines([
            "# This file is automatically generated by update_toc.py.\n",
            "# from toc.md. Please edit toc.md and not this file.\n"
        ])
        oneline = source.readline()
        while oneline != "":
            destination.writelines([
                oneline.replace('[', '')
                       .replace(']', '')
                       .replace('(', '')
                       .replace(')', '')
            ])
            oneline = source.readline()

