#!/usr/bin/env zsh

echo "Building Development Version. Please run 'make clean' before to be sure to build a clean version."
cp -f ../../kineticstoolkit/kineticstoolkit/DEVELOPMENT_VERSION KTK_VERSION
make html
cp -fR _build/html/* ../master/
open ../master/index.html
