#!/usr/bin/env zsh

echo "*******************"
echo "Building all clean."
echo "*******************"
make clean
./build_stable
echo "*******************"
make clean
./build_master
echo "*******************"
