#!/usr/bin/env zsh

echo "Building Development Version. Please run './clean' before to be sure to build a clean version."
touch KTK_AUTO_ENABLE_DEV
make html
cp -fR _build/html/* ../master/
open ../master/index.html
