#!/usr/bin/env zsh

echo "Building Stable Version. Please run './clean' before to be sure to build a clean version."
rm KTK_AUTO_ENABLE_DEV
make html
cp -fR _build/html/* ../stable/
open ../stable/index.html
