#!/usr/bin/env python3

"""
Tranform toc.md into myst.yml by stripping hypertext markdown syntax.
"""

TAB_LENGTH = 4


def write_line(destination, string):
    try:
        destination.writelines(
            [
                string.replace("[](", "")
                .replace(".md)", ".md")
            ]
        )
    except AttributeError:
        pass
        
    
current_section = ""
with open("toc.md", "r") as source:
    with open("myst.yml", "w") as destination:
        destination.writelines(
            [
                "# This file is automatically generated by update_toc.py.\n",
                "# from toc.md. Please edit toc.md and not this file.\n",
            ]
        )
        current_index = 0

        thisline = source.readline()

        # Parse the outline
        while thisline:
            write_line(destination, thisline)
            thisline = source.readline()
